export const GET_ARTICLES='get_articles'
export const ERROR_GLOBAL='error_global'
export const SUCCESS_GLOBAL='success_global'
export const CLEAR_NOTIFICATION='clear_noti'
export const AUTH_USER='auth_user'
export const SIGN_OUT='sign_out'
export const SITE_LAYOUT='site_layout'
export const GET_ARTICLE='get_article'